### ISSUE TITLE
整合出现问题

### ISSUE THREAD

**Issue by hxqtohxq** [hexagonframework/spring-data-ebean#2]
hello,我跟着readme 操作时候，出现了如下问题<code>You have defined query method in the repository but you don't have any query lookup strategy defined. The infrastructure apparently does not support query methods!</code> 我整合的spring boot 版本是 1.5.4Release  跟  spring-data-ebean 1.2.6 Release

**Comment by yuanxuegui** [comment]
@hxqtohxq EnableEbeanRepositories 默认使用的query lookup strategy是CREATE_IF_NOT_FOUND，请问单元测试可以跑吗？readme的demo在test里面都有。

**Comment by yuanxuegui** [comment]
已经重现。这个问题是由于 spring-data-ebean 1.2.6升级spring-data-commons到了2.0.x版本，而spring boot 1.5.x使用的spring-data-commons还是1.13.x版本，导致这个问题。 @hxqtohxq 可以升级spring boot至2.0.0.RC2或者排除spring boot的spring-data-commons来修复这个问题。
