### ISSUE TITLE
EbeanRepository 为什么要求实体必须实现 Persistable 接口

### ISSUE THREAD

**Issue by cn-src** [hexagonframework/spring-data-ebean#4]
必须实现 Persistable 接口这个无法理解，即便是必须要求有 id 的 jpa 也没有强制，是出于什么考虑呢？
```java
public interface EbeanRepository<T extends Persistable, ID extends Serializable>
```

**Comment by cn-src** [comment]
类似的，这些实现都没有采用泛型形参直接是实参定义，如果 id 不是 Long 就不行了。

```java
public abstract class AbstractEntity implements Persistable<Long>, Auditable<String, Long, LocalDateTime>
```

**Comment by yuanxuegui** [comment]
从实现上ebean不支持抽象基类上有泛型，所以提供的面向领域的ID采用常用的Long，作为关系型数据库的主键，DDD的业务键可以根据业务定义为字符串等类型。

**Comment by yuanxuegui** [comment]
强制id是从数据库设计规范角度和DDD实体与仓储接口设计角度考虑，任何实体都得有物理主键，根据业务添加其他加索引的业务键。

**Comment by cn-src** [comment]
强制id这个是没问题的，我是觉得不应该在 EbeanRepository 这个接口上做限制，可以像 hibernate 那样在初始化时检查，因为使用者不实现 Persistable 也可以给定 id，另外 Persistable 里还有个 isNew，这也不一定是想要的，毕竟 is 开头的也是一个 javabean 属性，而且 Persistable 接口并没有实现 isNew，这也就意味着使用者必须实现它，或者继承类似 AbstractEntity（此时id必须为Long） 。

以 Long 作为 id 也是类似的，无形中增加了限制。我觉得可以像 spring data jpa 那样设计，这样使用者能更加可自定义，毕竟像 UUID 也是是很常用的，这样就无法使用你预置的 AbstractEntity，然后提供一个 Long 为id的AbstractEntity实现（我觉得到这一步对于框架来说反而过细了，就像Repository一样也没有提供基于id类型的实现）。

**Comment by yuanxuegui** [comment]
EbeanRepository可以更新一版去掉实体要求，提供的抽象实体类保留现状，id其他类型可自定义抽象类

**Comment by yuanxuegui** [comment]
所以依赖的Spring data的PersistableEntityInformation要求实体必须继承Persistable

**Comment by cn-src** [comment]
PersistableEntityInformation 这个应该是如果你的实体继承了 Persistable 才会用到吧，如果不继承就不需要。

看 PersistableEntityInformation 的注释，如果你的实体继承了 Persistable 就用 `#isNew(Object)` 进行检查是否是新创建的对象。

没有的话我们可以判断 `@Id` 标注的字段是否为 null 来判断。可以关注到 `AbstractEntityInformation` 或者 `EntityInformation` 这一层级，可能会需要自己也实现个吧。

**Comment by cn-src** [comment]
看到了一个 `PersistentEntityInformation` 是否可以直接使用。

**Comment by yuanxuegui** [comment]
PersistentEntityInformation要实现spring data mapping的PersistentEntity，暂时还用不了。新版本基于EbeanServer的api直接实现了EntityInformation接口。
